# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nameaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=250)),
                ('email_text', models.CharField(max_length=250)),
                ('status_bool', models.BooleanField(default=1)),
                ('created_date', models.DateTimeField(verbose_name=b'date created')),
            ],
        ),
    ]
