# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170927_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameaddress',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
