# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170927_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameaddress',
            name='email_text',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
